version: "3.8"

services:

  paydock-extension:
    image: $IMAGE/extension:${CI_COMMIT_SHA}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    ports:
      - target: 8082
        published: 8082
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "CONNECT_SERVICE_URL=$CONNECT_SERVICE_URL"
    labels:
      - "filebeat_enable=true"
    networks:
      - proxy
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "5"

networks:
  proxy:
    external: true
    name: net_proxy

